# Functions for sent messages
FUNC_INIT_CONNECTION = "INIT_CONNECTION"
FUNC_CREATE_LEADERBOARD = "CREATE_LEADERBOARD"
FUNC_ADD_ENTRY = "ADD_ENTRY"
FUNC_REQUEST_LEADERBOARD = "REQUEST_LEADERBOARD"
FUNC_SEND_LEADERBOARD = "SEND_LEADERBOARD"
FUNC_ACK = "ACK"

MAX_MSG_LEN = 2048

USER_SERVER = "SERVER"